#pragma once
#define EVENT_ID_CHAT_COMMAND 400
#define EVENT_ID_SCREEN_UPDATE 401
#define EVENT_ID_KEY_INPUT 402
#define EVENT_ID_SCRIPT_LOADED 403
#define EVENT_ID_UNIT_DAMAGED 404
#define EVENT_ID_GAME_ENDED 405
#define EVENT_ID_ON_TICK 406