#pragma once

#define EVENT_DATA_ID_INPUTED_STRING 200
#define EVENT_DATA_ID_DAMAGE_SOURCE 201
#define EVENT_DATA_ID_DAMAGE_TARGET 202
#define EVENT_DATA_ID_DAMAGE_TYPE 203
#define EVENT_DATA_ID_ATTACK_TYPE 204
#define EVENT_DATA_ID_EVENT_DAMAGE 205
#define EVENT_DATA_ID_DAMAGE_FLAGS 206
#define EVENT_DATA_ID_INPUTED_KEY 207
#define EVENT_DATA_ID_INPUTED_KEY_MODE 208
#define EVENT_DATA_ID_PNETDATA 209