#pragma once
#include <BasicConstants.h>

int GetAbilityBaseDataById(DWORD aid);
int GetAbilityBaseDataByIdCaching(DWORD aid);
int GetAbilityBaseUIById(DWORD aid);
int GetAbilityBaseUICaching(DWORD aid);
void SetAbilityBaseHotkeyParam(DWORD aid, int off, int newVal);
int GetAbilityBaseHotkeyParam(DWORD aid, int off);
void SetAbilityBaseIntegerParam(DWORD aid, int off, int newVal);
int GetAbilityBaseIntegerParam(DWORD aid, int off);
void SetAbilityBaseRealParam(DWORD aid, int off, float newVal);
float GetAbilityBaseRealParam(DWORD aid, int off);
void SetAbilityBaseBoolParam(DWORD aid, int off, bool flag);
bool GetAbilityBaseBoolParam(DWORD aid, int off);
const char* GetAbilityBaseStringParam(DWORD aid, int off);
void SetAbilityBaseStringParam(DWORD aid, int off, const char* newVal);
const char* GetAbilityBaseStringParam2(DWORD aid, int off, int lvl);
void SetAbilityBaseStringParam2(DWORD aid, int off, const char* newVal, int lvl);
int GetAbilityBaseMaxLevel(DWORD aid);
int GetAbilityBaseManaCost(DWORD aid, int level);
void SetAbilityBaseManaCost(DWORD aid, int level, int cost);
float GetAbilityBaseCooldown(DWORD aid, int level);
void SetAbilityBaseCooldown(DWORD aid, int level, float cool);
const char* GetAbilityBaseEffectSound(DWORD aid);
void SetAbilityBaseEffectSound(DWORD aid, const char* s);
const char* GetAbilityBaseGlobalMessage(DWORD aid);
void SetAbilityBaseGlobalMessage(DWORD aid, const char* s);
const char* GetAbilityBaseGlobalSound(DWORD aid);
void SetAbilityBaseGlobalSound(DWORD aid, const char* s);
int GetAbilityBaseButtonX(DWORD aid);
void SetAbilityBaseButtonX(DWORD aid, int newX);
int GetAbilityBaseButtonY(DWORD aid);
void SetAbilityBaseButtonY(DWORD aid, int newY);
int GetAbilityBaseUnButtonX(DWORD aid);
void SetAbilityBaseUnButtonX(DWORD aid, int newX);
int GetAbilityBaseUnButtonY(DWORD aid);
void SetAbilityBaseUnButtonY(DWORD aid, int newY);
int GetAbilityBaseResearchButtonX(DWORD aid);
void SetAbilityBaseResearchButtonX(DWORD aid, int newX);
int GetAbilityBaseResearchButtonY(DWORD aid);
void SetAbilityBaseResearchButtonY(DWORD aid, int newY);
float GetAbilityBaseMissileSpeed(DWORD aid);
void SetAbilityBaseMissileSpeed(DWORD aid, float speed);
float GetAbilityBaseMissileArc(DWORD aid);
void SetAbilityBaseMissileArc(DWORD aid, float arc);
bool IsAbilityMissileHoming(DWORD aid);
void SetAbilityBaseMissileHoming(DWORD aid, bool homing);
int GetAbilityBaseSpellDetails(DWORD aid);
void SetAbilityBaseSpellDetails(DWORD aid, int det);
int GetAbilityBaseHotkeyId(DWORD aid);
void SetAbilityBaseHotkeyId(DWORD aid, int newVal);
int GetAbilityBaseUnHotkeyId(DWORD aid);
void SetAbilityBaseUnHotkeyId(DWORD aid, int newVal);
int GetAbilityBaseResearchHotkeyId(DWORD aid);
void SetAbilityBaseResearchHotkeyId(DWORD aid, int newVal);
const char* GetAbilityBaseTip(DWORD aid, int lvl);
void SetAbilityBaseTip(DWORD aid, int lvl, const char* s);
const char* GetAbilityBaseUbertip(DWORD aid, int lvl);
void SetAbilityBaseUbertip(DWORD aid, int lvl, const char* s);
void SetAbilityBaseHotkeyCommon(DWORD aid, int newVal);