#include <BasicConstants.h>
#include <Windows.h>
#include <Functions.h>

DWORD pJassEnvAddress;
DWORD dwGameState;
DWORD pGameState;
DWORD pConvertString;
DWORD pSearchStringValue;
DWORD pSearchStringAddr1;
DWORD pSearchStringAddr2;
DWORD pGameClass1;
DWORD pGetUnitAddress;
DWORD pGetHandleId;
DWORD pHandleIdToObject;
DWORD pObjectToHandleId;
DWORD pGetDataNode;
DWORD pGetAgentBaseData;
DWORD pToJUnit;
DWORD pUnitData;
DWORD pRedrawUnit;
DWORD pCommonSilence;
DWORD pPauseUnitDisabler;
DWORD pSetStunToUnit;
DWORD pUnsetStunToUnit;
DWORD pSetUnitTexture;
DWORD pGetHeroNeededXP;
DWORD pMorphUnitToTypeId;
DWORD pUpdateHeroBar;
DWORD pRefreshPortraitIfSelected;
DWORD pRefreshInfoBarIfSelected;
DWORD pPointers;
int* iGSpeed;
DWORD pnativescnt;
DWORD GAME_GlobalClass;
DWORD GAME_PrintToScreen;
DWORD pGlobalPlayerClass;
DWORD pWriteMemory;
DWORD pMergeUnits;
DWORD pIgnoredUnits;
DWORD pConvertUnits;
DWORD pMemcpy;
DWORD pGetModuleHandle;
DWORD pGetProcAddress;
DWORD pVirtualAlloc;
DWORD pSprintf;
DWORD pStorm279;
DWORD pStorm503;
DWORD pExportFromMPQ;
DWORD pSetObjectAlpha;
DWORD pSetObjectAnimation;
DWORD pExtrasPage;
DWORD pTriggerExecute;
DWORD pGetGameUI;
DWORD pUpdateUI;
DWORD pTextureLoadImageAnyExt;
DWORD pTextureUnloadImage;
DWORD pWorldFrameWar3UI;
DWORD pGetWindowWidth;
DWORD pGetWindowHeight;
DWORD pGetWarcraftWindow;
DWORD pGetAbilityBaseData;
DWORD pGetAbilityBaseUI;
DWORD pStartAbilityCD;
DWORD pSilenceAbility;
DWORD pUnsilenceAbility;
DWORD pGetUnitAbility;
DWORD pStringManager;
DWORD pFDFHashTableList;
DWORD pStringHashNodeGrowListArray;
DWORD pBaseFrameHashNodeGrowListArray;
DWORD pReadFDFFile;
DWORD pDefaultCStatus;
DWORD pGetCFrameByName;
DWORD pCreateCFrame;
DWORD pLoadCBackDropFrameTexture;
DWORD pGetCEditBoxText;
DWORD pSetCEditBoxText;
DWORD pSetCEditBoxFont;
DWORD pSetCEditBoxFocus;
DWORD pFindCLayerUnderCursor;
DWORD pSetCLayerOwner;
DWORD pHideCLayer;
DWORD pShowCLayer;
DWORD pSetCLayerAlpha;
DWORD pSetCLayerFont;
DWORD pSetCLayerTooltip;
DWORD pActiveCLayer;
DWORD pGetCLayoutFrameHeight;
DWORD pSetCLayoutFrameScale;
DWORD pSetCLayoutFramePoint;
DWORD pClearCLayoutFrameAllPoints;
DWORD pSetCLayoutFrameWidth;
DWORD pSetCLayoutFrameHeight;
DWORD pSetCLayoutFrameAbsolutePoint;
DWORD pSetCLayoutFrameCageMouse;
DWORD pSetCLayoutFrameAllPoints;
DWORD pAddCModelFrameModel;
DWORD pGetCModelFrameHeight;
DWORD pCreateCSimpleButton;
DWORD pSetCSimpleButtonState;
DWORD pSetCSimpleButtonStateTexture;
DWORD pCreateCSimpleFont;
DWORD pGetCSimpleFontByName;
DWORD pSetCSimpleFontText;
DWORD pSetCSimpleFontStringFont;
DWORD pGetCSimpleFontStringHeight;
DWORD pSetCSimpleFontStringScale;
DWORD pCreateCSimpleConsole;
DWORD pCreateCSimpleFrame;
DWORD pGetCSimpleFrameByName;
DWORD pSetCSimpleFrameScale;
DWORD pSetCSimpleFramePriority;
DWORD pSetCSimpleFrameParent;
DWORD pSetCSimpleGlueFrameScale;
DWORD pSetCSimpleMessageFrameFont;
DWORD pSetCSimpleRegionVertexColour;
DWORD pSetCSimpleStatusBarTexture;
DWORD pSetCSimpleStatusBarValue;
DWORD pSetCSimpleStatusBarMinMaxValue;
DWORD pCreateCSimpleTexture;
DWORD pFillCSimpleTexture;
DWORD pGetCSimpleTextureByName;
DWORD pSetCSimpleTextureTexture;
DWORD pSetCSliderCurrentValue;
DWORD pSetCSpriteFrameArt;
DWORD pGetCSpriteFrameHeight;
DWORD pSetCSpriteFrameScale;
DWORD pSetCStatusBarArt;
DWORD pSetCStatusBarMinMaxValue;
DWORD pSetCTextAreaText;
DWORD pGetCTextFrameHeight;
DWORD pSetCTextFrameText;
DWORD pSetCTextFrameTextColour;
DWORD pGetAxisZ;
DWORD pGetAgentInternal;
DWORD pGetPressenseTagged;
DWORD pAgentUpdate;
DWORD pSetWidgetPosition;
DWORD pSetWidgetCoordinates;
DWORD pCastAbility;
DWORD pOPLimitPos;
DWORD pGetTooltipFrame;
DWORD pGetFrameSkinByName;
DWORD pDestroyFrame;
DWORD pSetFrameState;
DWORD pClickFrame;
DWORD pUpdateFrame;
DWORD pGetUnitFramePosition;
DWORD pGroupGetUnitByIndex;
DWORD pItemDataNode;
DWORD pStartItemCD;
DWORD pGameClass2;
DWORD pGlobalMouseEvent;
DWORD pUnitDataNode;
DWORD pGetUnitUIData;
DWORD pStormAllocateMemory;
DWORD pStormFreeMemory;
DWORD pStormGetMemorySize;
DWORD pStormReallocateMemory;
DWORD pSetCBackDropFrameTexture;
DWORD pUnitFramePosition;
DWORD pGameUI;
DWORD pStorm266;
DWORD pStorm293;
DWORD pStorm252;
DWORD pStorm267;
DWORD pStorm590;
DWORD pStorm269;
DWORD pStorm253;
DWORD pStorm265;
DWORD pWidgetUnderCursor;
DWORD pProcessMouseEvent;
DWORD _SetMaxFps;
DWORD pSetAreaFOV;
DWORD WindowXoffset;
DWORD WindowYoffset;
DWORD pDisplayCommandBar;
DWORD pDrawSkillPanel;
DWORD pDisplayCommandBarIfNeeded;
DWORD pDWORDStunToUnit;
DWORD pUnDWORDStunToUnit;
DWORD pDWORDUnitTexture;
DWORD pCancelCurrentMode;
DWORD pCurrentMouseXRelative;
DWORD pCurrentMouseYRelative;
DWORD pSimpleTop;
DWORD pDrawAttackSpeed;
DWORD pDrawMoveSpeed;
DWORD pDrawItemText1;
DWORD pDrawItemText2;
DWORD pDrawUnitText1;
DWORD pDrawUnitText2;
DWORD pDrawDefTip;
DWORD pSetCIconConverTip;
DWORD pRealUnitAddAbilityAdv;
DWORD pRenderWorldObjects;
DWORD pJThreadRun;
DWORD pClickMouseWC3down;
DWORD pClickMouseWC3up;
DWORD pMouseScreenX;
DWORD pMouseScreenY;
DWORD pGetExTimerTimeElapsed;
DWORD pGetJassNameHandle;
DWORD pTickDuration;
DWORD pGetString;
DWORD pOnTick;
DWORD pGetEngineDataPointers;
DWORD pEnumObjectsInRange;
DWORD pEnumObjectsInRect;

DWORD pExtendedTickHook;
DWORD pExtendedTickHookRet;

void InitNativeConstants()
{
	pGetString = pGameDLL + 0x4c4630;
	pJassEnvAddress = pGameDLL + 0xADA848;
	dwGameState = dwGameDll + 0xAB65F4;
	pGameState = dwGameDll + 0xAB65F4;
	//pConvertString = pGameDLL + 0x3BAA20;
	pSearchStringValue = pGameDLL + 0x5C8ED0;
	pSearchStringAddr1 = pGameDLL + 0xACD23C;
	pSearchStringAddr2 = pGameDLL + 0xACD214;
	pGameClass1 = pGameDLL + 0xAB7788;
	pGetUnitAddress = pGameDLL + 0x3BDCB0;
	pGetHandleId = pGameDLL + 0x3A8060;
	pHandleIdToObject = pGameDLL + 0x428050;
	pObjectToHandleId = pGameDLL + 0x430C80;
	pGetDataNode = pGameDLL + 0x4C8520;
	pGetAgentBaseData = pGameDLL + 0x2B88A0;
	pToJUnit = pGameDLL + 0x2DCC40;
	pUnitData = pGameDLL + 0xAB4478;
	pRedrawUnit = pGameDLL + 0x284830;
	pCommonSilence = pGameDLL + 0x076770;
	pPauseUnitDisabler = pGameDLL + 0x0767F0;
	pSetStunToUnit = pGameDLL + 0x2A6440;
	pUnsetStunToUnit = pGameDLL + 0x282B30;
	pSetUnitTexture = pGameDLL + 0x4D32E0;
	pGetHeroNeededXP = pGameDLL + 0x26EB50;
	pMorphUnitToTypeId = pGameDLL + 0x2A1F20;
	pUpdateHeroBar = pGameDLL + 0x26FE50;
	pRefreshPortraitIfSelected = pGameDLL + 0x26FE10;
	pRefreshInfoBarIfSelected = pGameDLL + 0x26FE20;
	pPointers = ReadRealMemory(pGameDLL + 0xAB7788);
	iGSpeed = (int*)(dwGameDll + 0x55363A);
	pnativescnt = dwGameDll + 0xAB72C4;
	GAME_GlobalClass = dwGameDll + 0xAB4F80;
	GAME_PrintToScreen = dwGameDll + 0x2F8E40;
	pGlobalPlayerClass = dwGameDll + 0xAB65F4;
	pJassEnvAddress = pGameDLL + 0xADA848;
	pWriteMemory = pGameDLL + 0xBE6188;
	pPointers = ReadRealMemory(pGameDLL + 0xAB7788);
	pMergeUnits = pGameDLL + 0x2DD320;
	pIgnoredUnits = pGameDLL + 0x2DCE80;
	pConvertUnits = pGameDLL + 0x2DD2E0;
	pMemcpy = pGameDLL + 0x86D3CC;
	pGetModuleHandle = pGameDLL + 0x86D1D0;
	pGetProcAddress = pGameDLL + 0x86D280;
	pVirtualAlloc = pGameDLL + 0x86D0F4;
	pConvertString = pGameDLL + 0x3BAA20;
	pSearchStringValue = pGameDLL + 0x5C8ED0;
	pSearchStringAddr1 = pGameDLL + 0xACD23C;
	pSearchStringAddr2 = pGameDLL + 0xACD214;
	pSprintf = pGameDLL + 0x86D32C;
	pGameState = pGameDLL + 0xAB65F4;
	pGameClass1 = pGameDLL + 0xAB7788;
	pGetUnitAddress = pGameDLL + 0x3BDCB0;
	pGetHandleId = pGameDLL + 0x3A8060;
	pHandleIdToObject = pGameDLL + 0x428050;
	pGetDataNode = pGameDLL + 0x4C8520;
	pGetAgentBaseData = pGameDLL + 0x2B88A0;
	pToJUnit = pGameDLL + 0x2DCC40;
	pStorm279 = pGameDLL + 0x86D5B8;
	pExportFromMPQ = pGameDLL + 0x737F00;
	pSetObjectAlpha = pGameDLL + 0x4D3250;
	pSetObjectAnimation = pGameDLL + 0x4D7C00;
	pExtrasPage = pGameDLL + 0x5C4120;
	pTriggerExecute = pGameDLL + 0x3C3F40;
	pGetGameUI = pGameDLL + 0x300710;
	pUpdateUI = pGameDLL + 0x332700;
	pTextureLoadImageAnyExt = pGameDLL + 0x727C00;
	pTextureUnloadImage = pGameDLL + 0x4DE1B0;
	pWorldFrameWar3UI = pGameDLL + 0x941550;
	pGetWindowWidth = pGameDLL + 0xADE91C;
	pGetWindowHeight = pGameDLL + 0xADE918;
	pGetWarcraftWindow = pGameDLL + 0x6BAD70;
	pGetAbilityBaseData = pGameDLL + 0x265ED0;
	pGetAbilityBaseUI = pGameDLL + 0x32C8E0;
	pStartAbilityCD = pGameDLL + 0x050B70;
	pSilenceAbility = pGameDLL + 0x052B60;
	pUnsilenceAbility = pGameDLL + 0x052BC0;
	pGetUnitAbility = pGameDLL + 0x0787D0;
	pStringManager = pGameDLL + 0xACD214;
	pFDFHashTableList = pGameDLL + 0xACD264;
	pStringHashNodeGrowListArray = pGameDLL + 0x5CA9B0;
	pBaseFrameHashNodeGrowListArray = pGameDLL + 0x5D5650;
	pReadFDFFile = pGameDLL + 0x5D8DE0;
	pDefaultCStatus = pGameDLL + 0xA8C804;
	pGetCFrameByName = pGameDLL + 0x5FA970;
	pCreateCFrame = pGameDLL + 0x5C9560;
	pLoadCBackDropFrameTexture = pGameDLL + 0x620FE0;
	pGetCEditBoxText = pGameDLL + 0x613EA0;
	pSetCEditBoxText = pGameDLL + 0x615B50;
	pSetCEditBoxFont = pGameDLL + 0x613CA0;
	pSetCEditBoxFocus = pGameDLL + 0x615180;
	pFindCLayerUnderCursor = pGameDLL + 0x5FDA20;
	pSetCLayerOwner = pGameDLL + 0x5FF6D0;
	pHideCLayer = pGameDLL + 0x5FE6F0;
	pShowCLayer = pGameDLL + 0x5FE690;
	pSetCLayerAlpha = pGameDLL + 0x5FDEC0;
	pSetCLayerFont = pGameDLL + 0x5FB960;
	pSetCLayerTooltip = pGameDLL + 0x5FF800;
	pActiveCLayer = pGameDLL + 0xACE66C;
	pGetCLayoutFrameHeight = pGameDLL + 0x604FA0;
	pSetCLayoutFrameScale = pGameDLL + 0x605D40;
	pSetCLayoutFramePoint = pGameDLL + 0x606770;
	pClearCLayoutFrameAllPoints = pGameDLL + 0x606270;
	pSetCLayoutFrameWidth = pGameDLL + 0x605D90;
	pSetCLayoutFrameHeight = pGameDLL + 0x605DB0;
	pSetCLayoutFrameAbsolutePoint = pGameDLL + 0x6061B0;
	pSetCLayoutFrameCageMouse = pGameDLL + 0x604FC0;
	pSetCLayoutFrameAllPoints = pGameDLL + 0x6067F0;
	pAddCModelFrameModel = pGameDLL + 0x6215D0;
	pGetCModelFrameHeight = pGameDLL + 0x621960;
	pCreateCSimpleButton = pGameDLL + 0x6030E0;
	pSetCSimpleButtonState = pGameDLL + 0x602FE0;
	pSetCSimpleButtonStateTexture = pGameDLL + 0x603220;
	pCreateCSimpleFont = pGameDLL + 0x60D580;
	pGetCSimpleFontByName = pGameDLL + 0x61C7B0;
	pSetCSimpleFontText = pGameDLL + 0x60CA10;
	pSetCSimpleFontStringFont = pGameDLL + 0x60DA20;
	pGetCSimpleFontStringHeight = pGameDLL + 0x60CF70;
	pSetCSimpleFontStringScale = pGameDLL + 0x60DCD0;
	pCreateCSimpleConsole = pGameDLL + 0x5C9610;
	pCreateCSimpleFrame = pGameDLL + 0x609C70;
	pGetCSimpleFrameByName = pGameDLL + 0x61C770;
	pSetCSimpleFrameScale = pGameDLL + 0x609A20;
	pSetCSimpleFramePriority = pGameDLL + 0x2F59B0;
	pSetCSimpleFrameParent = pGameDLL + 0x609980;
	pSetCSimpleGlueFrameScale = pGameDLL + 0x616AD0;
	pSetCSimpleMessageFrameFont = pGameDLL + 0x603B10;
	pSetCSimpleRegionVertexColour = pGameDLL + 0x60E740;
	pSetCSimpleStatusBarTexture = pGameDLL + 0x60E610;
	pSetCSimpleStatusBarValue = pGameDLL + 0x60E430;
	pSetCSimpleStatusBarMinMaxValue = pGameDLL + 0x60E3B0;
	pCreateCSimpleTexture = pGameDLL + 0x60D900;
	pFillCSimpleTexture = pGameDLL + 0x60D3B0;
	pGetCSimpleTextureByName = pGameDLL + 0x61C790;
	pSetCSimpleTextureTexture = pGameDLL + 0x60E090;
	pSetCSliderCurrentValue = pGameDLL + 0x61EE70;
	pSetCSpriteFrameArt = pGameDLL + 0x60F360;
	pGetCSpriteFrameHeight = pGameDLL + 0x60EB00;
	pSetCSpriteFrameScale = pGameDLL + 0x60EE60;
	pSetCStatusBarArt = pGameDLL + 0x6279A0;
	pSetCStatusBarMinMaxValue = pGameDLL + 0x6277C0;
	pSetCTextAreaText = pGameDLL + 0x61E090;
	pGetCTextFrameHeight = pGameDLL + 0x6118A0;
	pSetCTextFrameText = pGameDLL + 0x611D40;
	pSetCTextFrameTextColour = pGameDLL + 0x611590;
	pGetAxisZ = pGameDLL + 0x24F3E0;
	pGetAgentInternal = pGameDLL + 0x4786B0;
	pGetPressenseTagged = pGameDLL + 0x03FA30;
	pAgentUpdate = pGameDLL + 0x282E40;
	pSetWidgetPosition = pGameDLL + 0x2B6AE0;
	pSetWidgetCoordinates = pGameDLL + 0x2AC220;
	pCastAbility = pGameDLL + 0x05C3A0;
	pOPLimitPos = pGameDLL + 0x3A838C;
	pGetTooltipFrame = pGameDLL + 0x337240;
	pGetFrameSkinByName = pGameDLL + 0x31F530;
	pDestroyFrame = pGameDLL + 0x606910;
	pSetFrameState = pGameDLL + 0x336C20;
	pClickFrame = pGameDLL + 0x601F20;
	pUpdateFrame = pGameDLL + 0x605CC0;
	pGetUnitFramePosition = pGameDLL + 0x334180;
	pGroupGetUnitByIndex = pGameDLL + 0x421A20;
	pItemDataNode = pGameDLL + 0xAB4BCC;
	pStartItemCD = pGameDLL + 0x0E3F30;
	pGameClass2 = pGameDLL + 0xAB4F80;
	pGlobalMouseEvent = pGameDLL + 0xA9A434;
	pUnitDataNode = pGameDLL + 0xAB445C;
	pGetUnitUIData = pGameDLL + 0x32C880;
	pStormAllocateMemory = dwStormDll + 0x025F30;
	pStormFreeMemory = dwStormDll + 0x024880;
	pStormGetMemorySize = dwStormDll + 0x024AD0;
	pStormReallocateMemory = dwStormDll + 0x026230;
	pSetCBackDropFrameTexture = pGameDLL + 0x6212D0;
	pStorm266 = GetProc(dwStormDll,266);
	pStorm293 = GetProc(dwStormDll, 293);
	pStorm252 = GetProc(dwStormDll, 252);
	pStorm267 = GetProc(dwStormDll, 267);
	pStorm269 = GetProc(dwStormDll, 269);
	pStorm590 = GetProc(dwStormDll, 590);
	pStorm253 = GetProc(dwStormDll, 253);
	pStorm265 = GetProc(dwStormDll, 265);
	pStorm503 = GetProc(dwStormDll, 503);
	pUnitFramePosition = (DWORD)malloc(0x8);
	pWidgetUnderCursor = pGameDLL + 0xAB62D4;
	pProcessMouseEvent = pGameDLL + 0x631490;
	_SetMaxFps = pGameDLL + 0x383640;
	pSetAreaFOV = pGameDLL + 0x7B66F0;
	WindowXoffset = (pGameDLL + 0xADE91C);
	WindowYoffset = (pGameDLL + 0xADE918);
	pDisplayCommandBar = (pGameDLL + 0x285DC0);
	pDrawSkillPanel = (pGameDLL + 0x2774C0);
	pDisplayCommandBarIfNeeded = pGameDLL + 0x34F280;
	pDWORDStunToUnit = pGameDLL + 0x2A6440;
	pUnDWORDStunToUnit = pGameDLL + 0x282B30;
	pDWORDUnitTexture = pGameDLL + 0x4D32E0;
	pCancelCurrentMode = pGameDLL + 0x2FB920;
	pCurrentMouseXRelative = pGameDLL + 0xA9A458;
	pCurrentMouseYRelative = pGameDLL + 0xA9A45C;
	pCancelCurrentMode = pGameDLL + 0x2FB920;
	pSimpleTop = pGameDLL + 0xACE758;
	pDrawAttackSpeed = pGameDLL + 0x339150;
	pDrawMoveSpeed = pGameDLL + 0x338FB0;
	pDrawItemText1 = pGameDLL + 0x369e72;
	pDrawItemText2 = pGameDLL + 0x369ee6;
	pDrawUnitText1 = pGameDLL + 0x358198;
	pDrawUnitText2 = pGameDLL + 0x3583c2;
	pDrawDefTip= pGameDLL + 0x3543da;
	pSetCIconConverTip = pGameDLL + 0x3535d0;
	pRealUnitAddAbilityAdv = pGameDLL + 0x24cdf0;
	pRenderWorldObjects = pGameDLL + 0x395620;
	pJThreadRun = pGameDLL + 0x45e9d0;
	pClickMouseWC3down = pGameDLL + 0x630f60;
	pClickMouseWC3up = pGameDLL + 0x6310a0;
	pMouseScreenX = pGameDLL + 0xAD1480;
	pMouseScreenY = pGameDLL + 0xAD1484;
	pGetExTimerTimeElapsed = pGameDLL + 0x477b80;
	pGetJassNameHandle = pGameDLL + 0x39f5b0;
	pTickDuration = pGameDLL + 0xacc8cc;
	pOnTick = pGameDLL + 0x553470;
	pGetEngineDataPointers = pGameDLL + 0x4c34d0;
	pEnumObjectsInRange = pGameDLL + 0x467570;
	pEnumObjectsInRect = pGameDLL + 0x4693d0;

	pExtendedTickHook    = pGameDLL+ 0x55377b;
	pExtendedTickHookRet = pGameDLL+ 0x553780;

}