#pragma once
typedef unsigned int jHANDLE;
bool IsTrackableHidden(jHANDLE track);
void ShowTrackable(jHANDLE track, bool flag);
void SetTrackableAlpha(jHANDLE track, int alpha);
int GetTrackableColour(jHANDLE track);
void SetTrackableColour(jHANDLE track, int colour);
void SetTrackableColourEx(jHANDLE track, int red, int green, int blue, int alpha);
void SetTrackableVertexColour(jHANDLE track, int red, int green, int blue, int alpha);
int GetTrackableColourA(jHANDLE track);
void SetTrackableColourA(jHANDLE track, int alpha);
int GetTrackableColourR(jHANDLE track);
void SetTrackableColourR(jHANDLE track, int red);
int GetTrackableColourG(jHANDLE track);
void SetTrackableColourG(jHANDLE track, int green);
int GetTrackableColourB(jHANDLE track);
void SetTrackableColourB(jHANDLE track, int blue);
void SetTrackableAnimationByIndex(jHANDLE track, int index);
void SetTrackableModel(jHANDLE track, const char* model);
float GetTrackableX(jHANDLE track);
void SetTrackableX(jHANDLE track, float x);
float GetTrackableY(jHANDLE track);
void SetTrackableY(jHANDLE track, float y);
float GetTrackableZ(jHANDLE track);
void SetTrackableZ(jHANDLE track, float z);
void SetTrackablePosition(jHANDLE track, float x, float y, float z);
float GetTrackableTimeScale(jHANDLE track);
void SetTrackableTimeScale(jHANDLE track, float speed);
float GetTrackableScale(jHANDLE track);
void SetTrackableScale(jHANDLE track, float scale);
void SetTrackableScaleEx(jHANDLE track, float x, float y, float z);
void SetTrackableSpaceRotation(jHANDLE track, float yaw, float pitch, float roll);
float GetTrackableRoll(jHANDLE track);
void SetTrackableRoll(jHANDLE track, float angle);
float GetTrackablePitch(jHANDLE track);
void SetTrackablePitch(jHANDLE track, float angle);
float GetTrackableFacing(jHANDLE track);
void SetTrackableFacing(jHANDLE track, float angle);
void ResetTrackableMatrix(jHANDLE track);