#pragma once

int GetARGBColour(char alpha, char red, char green, char blue);
float GetSpriteDataOffsetAddressR(int pObject, int offset);
void SetSpriteDataOffsetAddressR(int pObject, int offset, float r);
bool IsObjectHidden(int pObject);
void ShowObject(int pObject, bool flag);
int GetObjectTypeId(int pObj);
void UpdateObjectColour(int pObject);
void SetObjectAlpha(int pObject, int alpha);
int GetObjectColour(int pObject);
void SetObjectColour(int pObject, int colour);
void SetObjectColourEx(int pObject, int red, int green, int blue, int alpha);
void SetObjectVertexColour(int pObject, int red, int green, int blue, int alpha);
int GetObjectColourA(int pObject);
void SetObjectColourA(int pObject, int alpha);
int GetObjectColourR(int pObject);
void SetObjectColourR(int pObject, int red);
int GetObjectColourG(int pObject);
void SetObjectColourG(int pObject, int green);
int GetObjectColourB(int pObject);
void SetObjectColourB(int pObject, int blue);
void SetObjectAnimationByIndex(int pObject, int index);
void SetObjectModel(int pObject, const char* model);
float GetObjectX(int pObject);
void SetObjectX(int pObject, float x);
float GetObjectY(int pObject);
void SetObjectY(int pObject, float y);
float GetObjectZ(int pObject);
void SetObjectZ(int pObject, float z);
void SetObjectPosition(int pObject, float x, float y, float z);
float GetObjectTimeScale(int pObject);
void SetObjectTimeScale(int pObject, float speed);
float GetObjectScale(int pObject);
void SetObjectScale(int pObject, float scale);
void SetObjectScaleEx(int pObject, float x, float y, float z);
void SetObjectSpaceRotation(int pObject, float yaw, float pitch, float roll);
float GetObjectRoll(int pObject);
void SetObjectRoll(int pObject, float angle);
float GetObjectPitch(int pObject);
void SetObjectPitch(int pObject, float angle);
float GetObjectFacing(int pObject);
void SetObjectFacing(int pObject, float angle);
void ResetObjectMatrix(int pObject);
