#pragma once
#include <BasicConstants.h>

DWORD GetUnitBaseDataById(int uid);
DWORD GetUnitBaseData(jHANDLE u);
DWORD GetUnitBaseDataByIdCaching(DWORD uid);
DWORD GetUnitBaseDataCaching(jHANDLE u);
DWORD GetUnitBaseUIDataById(DWORD uid);
DWORD GetUnitBaseUIData(jHANDLE u);
DWORD GetUnitBaseUIDataByIdCaching(DWORD uid);
DWORD GetUnitBaseUIDataCaching(jHANDLE u);
DWORD GetUnitBaseUIIntegerParam(DWORD uid, int includedLevel, int offset);
void SetUnitBaseUIIntegerParam(DWORD uid, int includedLevel, int offset, int val);
const char* GetUnitBaseUIStringParam(DWORD uid, int includedLevel, int offset);
void SetUnitBaseUIStringParam(DWORD uid, int includedLevel, int offset, const char* val);
const char* GetUnitBasePortraitById(DWORD uid);
void SetUnitBasePortraitById(DWORD uid, const char* model);
const char* GetUnitBaseMissileArtById(DWORD uid, const char* path);
void SetUnitBaseMissileArtById(DWORD uid, const char* model);
float GetUnitBaseMissileSpeedById(DWORD uid, int index);
void SetUnitBaseMissileSpeedById(DWORD uid, DWORD index, float speed);
int GetUnitBaseColorById(int uid);
const char* GetUnitBaseModelById(int uid);
void SetUnitBaseModelById(DWORD uid, const char* model);
const char* GetUnitBaseTipById(DWORD uid);
void SetUnitBaseTipById(DWORD uid, const char* text);
const char* GetUnitBaseUbertipById(DWORD uid);
void SetUnitBaseUbertipById(DWORD uid, const char* text);
int GetUnitBaseHotkeyById(DWORD uid);
void SetUnitBaseHotkeyById(DWORD uid, DWORD key);
const char* GetUnitBaseModel(jHANDLE u);
void SetUnitBaseModel(jHANDLE u, const char* model);
const char* GetUnitBasePortrait(jHANDLE u);
void SetUnitBasePortrait(jHANDLE u, const char* model);
const char* GetUnitBaseMissileArt(jHANDLE u, const char* model);
void SetUnitBaseMissileArt(jHANDLE u, const char* model);
float GetUnitBaseMissileSpeed(jHANDLE u, int index);
void SetUnitBaseMissileSpeed(jHANDLE u, int index, float speed);
int GetUnitBaseColor(jHANDLE u);
const char* GetUnitBaseTip(jHANDLE u);
void SetUnitBaseTip(jHANDLE u, const char* text);
const char* GetUnitBaseUbertip(jHANDLE u);
void SetUnitBaseUbertip(jHANDLE u, const char* text);
DWORD GetUnitBaseHotkey(jHANDLE u);
void SetUnitBaseHotkey(jHANDLE u, DWORD key);
DWORD GetHeroBasePrimaryAttributeById(DWORD uid);
void SetHeroBasePrimaryAttributeById(int uid, int index);
int GetHeroBasePrimaryAttribute(jHANDLE u);
void SetHeroBasePrimaryAttribute(jHANDLE u, int index);